import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: '#222222',
		alignItems: 'center',
	},
	headerContainer: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		height: 100,
		width: '100%',
		backgroundColor: 'white',
	},
	navMenu: {
		padding: 20,
	},
	navText: {
		color: 'white',
		fontSize: 20,
	},
	bodyContainer: {
		flex: 1,
		alignContent: 'center',
		justifyContent: 'center',
		height: 100,
		width: '90%',
	},
	text: {
		color: 'white',
		alignSelf: 'center',
	},
	inputStyle: {
		color: '#a4a4a4',
		paddingTop: 16,
		paddingBottom: 16,
		borderWidth: 1,
		borderStyle: 'solid',
		borderBottomColor: '#BEAD8E',
		borderTopColor: 'transparent',
		borderLeftColor: 'transparent',
		borderRightColor: 'transparent',
		fontSize: 19,
	},
	inputLabel: {
		color: 'white',
		fontSize: 22,
	},
	buttonStyle: {
		position: 'absolute',
		bottom: 5,
		alignItems: 'center',
		justifyContent: 'center',
		paddingVertical: 32,
		width: '100%',
		borderRadius: 5,
		backgroundColor: '#BEAD8E',
		color: 'white',
	},
	buttonDisabled: {
		position: 'absolute',
		bottom: 5,
		alignItems: 'center',
		justifyContent: 'center',
		paddingVertical: 32,
		width: '100%',
		borderRadius: 5,
		color: 'white',
		backgroundColor: 'gray',
		opacity: 0.5,
	},
	buttonText: {
		fontSize: 16,
		lineHeight: 21,
		fontWeight: 'bold',
		letterSpacing: 0.25,
		color: 'white',
	},
	imageStyle: {
		width: 120,
		height: 35,
		resizeMode: 'contain',
	},
	infoContainer: {
		flex: 1,
		alignContent: 'center',
		justifyContent: 'center',
		gap: 30,
		width: '90%',
	},
	tableTitle: {
		color: 'white',
		fontSize: 30,
		fontWeight: 'bold',
		textAlign: 'center',
	},
	tableText: {
		color: 'white',
		borderWidth: 1,
		borderStyle: 'solid',
		borderColor: 'white',
		width: '100%',
		padding: 10,
		textAlign: 'center',
		fontSize: 12,
	},
})
